### ISSUE TITLE
请问如下的数据结构，是否可用dTable合并单元格显示；若可以合并的代码如何编写

### ISSUE THREAD

**Issue by Chouna** [dean5277/iviewxx#3]
[
	{
		key: '实例用途',
		values: [
			{
				name: '开发',
				value: '1',
				order: 1
			},
			{
				name: '测试',
				value: '2',
				order: 2
			},
			{
				name: '准生产',
				value: '3',
				order: 3
			},
			{
				name: '生产',
				value: '4',
				order: 4
			}
		]
	},
	{
		key: 'Address类型',
		values: [
			{
				name: '公网',
				value: 'internet',
				order: 1
			},
			{
				name: '私网',
				value: 'intranet',
				order: 2
			}
		]
	}
]

**Comment by dean5277** [comment]
不支持这种数据结构
