### ISSUE TITLE
dTable 组件，列宽拖动问题

### ISSUE THREAD

**Issue by jekip** [dean5277/iviewxx#5]
第一次拖动之后，在表头点击，会出现，宽度随机变化，
控制台报错：iview.js:22787 Uncaught TypeError: Cannot read property 'width' of undefined
    at VueComponent.scheduleLayout (iview.js:22787)
    at VueComponent.<anonymous> (iview.js:22763)
不知道是不是和官方的iview冲突，我是用的iview 然后在组件内单独引入了 dTable 组件 使用，列宽拖动该怎么关闭呢？

**Comment by dean5277** [comment]
拖动列宽都是自动开启的，暂时没有关闭的功能。

其实你直接用iviewxx就好了，完全兼容iview的
